name: Website Monitor

on:
  schedule:
    - cron: "*/10 * * * *" # every 10 minutes
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run monitor
        env:
          TELEGRAM_TOKEN: ${{ 8365333559:AAH7oCneaw61NSFHp-jVBnIW0QX8pHTgq-M }}
          TELEGRAM_CHAT_ID: ${{ 8528165371 }}
        run: |
          chmod +x check.sh
          ./check.sh
